# Generated by Django 6.0.2 on 2026-02-14 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=200)),
                ('drink_description', models.TextField(blank=True, max_length=200, null=True)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True, max_length=200, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reservation_Name', models.CharField(help_text='*required', max_length=200)),
                ('Requested_Date', models.DateField(help_text='*required')),
                ('Requested_Time', models.TimeField(help_text='*required')),
                ('Party_Size', models.PositiveIntegerField(help_text='*required', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('special_Requests', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
